-- write a SQL query to calculate the total order amount generated by a salesperson. 
--Salespersons should be from the cities where the customers reside. Return salesperson name, city and total order amount

select salesman.name,salesman.city,suquery1.total_amt from
salesman,(select salesman_id,sum(orders.purch_amt) as total_amt
from orders group by salesman_id) suquery1 where suquery1.salesman_id=salesman.salesman_id
and salesman.city in (select distinct city from customer)

